### ISSUE TITLE
Sees Temp of Room and sends commands with no action to mini split

### ISSUE THREAD

**Issue by okieplaya** [ryanfroese/homebridge-smartcielo#1]
**Describe The Bug:**

Reeds Temp of the Room and HomeBridge show Power on command and set cool but the Unit does not respond at all.
**To Reproduce:**

Homebridge Accessories or homekit 
Click Room 
Room Tstat 
Pick cool or heat 
chose temp set point

**Expected behavior:**

Mini split unit from off mode should 
turn on
set cool/Heat
![Model Number Firmware ver](https://user-images.githubusercontent.com/131422179/233532213-71b4e9cb-8af7-450b-a68a-5358a6cfff83.jpg)

set temp set point 
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```
[4/20/2023, 9:33:31 PM] [homebridge-cielo] Sending power on
[4/20/2023, 9:33:41 PM] [homebridge-cielo] Setting mode to cool
[4/20/2023, 9:38:44 PM] [Homebridge UI] Changes to config.json saved.
[4/20/2023, 9:38:48 PM] [homebridge-cielo] Restarting child bridge...
[4/20/2023, 9:38:48 PM] Got SIGTERM, shutting down child bridge process...
[4/20/2023, 9:38:53 PM] [homebridge-cielo] Child bridge process ended
[4/20/2023, 9:38:53 PM] [homebridge-cielo] Process Ended. Code: 143, Signal: null
[4/20/2023, 9:39:00 PM] [homebridge-cielo] Restarting Process...
[4/20/2023, 9:39:01 PM] [homebridge-cielo] Launched child bridge with PID 1274
[4/20/2023, 9:39:01 PM] Registering platform 'homebridge-cielo.cielo'
[4/20/2023, 9:39:01 PM] [homebridge-cielo] Loaded homebridge-cielo v1.1.2 child bridge successfully
[4/20/2023, 9:39:01 PM] Loaded 1 cached accessories from cachedAccessories.0E9E6427F249.
[4/20/2023, 9:39:01 PM] [homebridge-cielo] Loading accessory from cache: Game Room
[4/20/2023, 9:39:01 PM] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-cielo) is running on port 47595.
[4/20/2023, 9:39:03 PM] [homebridge-cielo] Restoring existing accessory from cache: Game Room
[4/20/2023, 9:40:59 PM] [homebridge-cielo] Sending power on
[4/20/2023, 9:41:09 PM] [homebridge-cielo] Setting mode to cool
[4/20/2023, 9:52:01 PM] [homebridge-cielo] Communication Error: Error: Connection Closed.
    at WebSocket.<anonymous> (/homebridge/node_modules/homebridge-cielo/node_modules/node-smartcielo-ws/Cielo.js:158:27)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/homebridge/node_modules/homebridge-cielo/node_modules/ws/lib/websocket.js:246:10)
    at TLSSocket.socketOnClose (/homebridge/node_modules/homebridge-cielo/node_modules/ws/lib/websocket.js:1148:15)
    at TLSSocket.emit (node:events:525:35)
    at node:net:320:12
    at TCP.done (node:_tls_wrap:588:7)
[4/20/2023, 9:52:01 PM] [homebridge-cielo] Reconnecting in 30 seconds...
[4/20/2023, 9:52:33 PM] [homebridge-cielo] Restoring existing accessory from cache: Game Room**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```
{
    "username": "my login",
    "password": "mypassword",
    "ip": "my home pub static ip",
    "macAddresses": [
        "E8DB8486780A"
    ],
    "_bridge": {
        "username": "0E:9E:64:27:F2:49",
        "port": 47595
    },
    "platform": "cielo"
}

**Screenshots:**

**Environment:**
Local Network No Vlans 
* **Plugin Version**: homebridge-cielo v1.1.2
* **Homebridge Version**:  [v1.6.0]
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:  Docker
*

**Comment by okieplaya** [comment]
this is what I get if i manually turn it on from the cielowigle home app this feed back from the unit. 


[4/20/2023, 10:41:10 PM] [homebridge-cielo] Sending power on
[4/20/2023, 10:41:20 PM] [homebridge-cielo] Setting mode to cool
[4/20/2023, 10:41:20 PM] [homebridge-cielo] Sending power on
[4/20/2023, 10:41:29 PM] [homebridge-cielo] Setting temperature to 69 °F / 20.6 °C
[4/20/2023, 10:41:30 PM] [homebridge-cielo] Setting mode to cool
[4/20/2023, 10:41:32 PM] [homebridge-cielo] Setting temperature to 70 °F / 21.1 °C
[4/20/2023, 10:41:38 PM] [homebridge-cielo] Sending power on
[4/20/2023, 10:41:42 PM] [homebridge-cielo] Setting temperature to 73 °F / 22.8 °C
[4/20/2023, 10:41:44 PM] [homebridge-cielo] Setting temperature to 71 °F / 21.7 °C
[4/20/2023, 10:41:48 PM] [homebridge-cielo] Setting mode to heat
[4/20/2023, 10:47:50 PM] [homebridge-cielo] This plugin generated a warning from the characteristic 'Current Heating Cooling State': characteristic was supplied illegal value: number 3 exceeded maximum of 2. See https://homebridge.io/w/JtMGR for more info.
[4/20/2023, 10:48:11 PM] [homebridge-cielo] Setting temperature to 71 °F / 21.7 °C
[4/20/2023, 10:48:56 PM] [homebridge-cielo] This plugin generated a warning from the characteristic 'Current Heating Cooling State': characteristic was supplied illegal value: number 3 exceeded maximum of 2. See https://homebridge.io/w/JtMGR for more info.
[4/20/2023, 10:48:58 PM] [homebridge-cielo] This plugin generated a warning from the characteristic 'Current Heating Cooling State': characteristic was supplied illegal value: number 3 exceeded maximum of 2. See https://homebridge.io/w/JtMGR for more info.

**Comment by ryanfroese** [comment]
If you still have this, give it a shot! I just got mine working, but had to add a captcha solver to do so (they added captcha's to their API)
