### ISSUE TITLE
 Communication Error: Error: Connection Closed AND This plugin threw an error...

### ISSUE THREAD

**Issue by m3rg3d0wn** [ryanfroese/homebridge-smartcielo#4]
Thanks for getting this plugin up and running. I can see it in HomeKit and it seems to show me the temp and if the AC unit is running. When I send a command, it seems to fail.

[31/07/2023, 13:00:42] [cielo] Setting mode to auto
[31/07/2023, 13:00:42] [cielo] Communication Error: Error: Connection Closed.
    at WebSocket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-cielo/node_modules/node-smartcielo-ws/Cielo.js:159:27)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emitClose (/var/lib/homebridge/node_modules/homebridge-cielo/node_modules/ws/lib/websocket.js:246:10)
    at Receiver.receiverOnFinish (/var/lib/homebridge/node_modules/homebridge-cielo/node_modules/ws/lib/websocket.js:1058:20)
    at Receiver.emit (node:events:513:28)
    at finish (node:internal/streams/writable:748:10)
    at node:internal/streams/writable:726:13
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[31/07/2023, 13:00:42] [cielo] Reconnecting in 30 seconds...
[31/07/2023, 13:00:46] [cielo] Sending power off
[31/07/2023, 13:00:46] [homebridge-cielo] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: log is not defined. See https://homebridge.io/w/JtMGR for more info.
[31/07/2023, 13:00:51] [cielo] Setting mode to auto
[31/07/2023, 13:00:51] [homebridge-cielo] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: log is not defined. See https://homebridge.io/w/JtMGR for more info.
[31/07/2023, 13:00:53] [cielo] Setting temperature to 66 °F / 18.9 °C
[31/07/2023, 13:00:53] [homebridge-cielo] This plugin threw an error from the characteristic 'Target Temperature': Unhandled error thrown inside write handler for characteristic: log is not defined. See https://homebridge.io/w/JtMGR for more info.
[31/07/2023, 13:01:01] [cielo] Setting mode to auto
[31/07/2023, 13:01:01] [homebridge-cielo] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: log is not defined. See https://homebridge.io/w/JtMGR for more info.
[31/07/2023, 13:01:05] [cielo] Setting mode to auto
[31/07/2023, 13:01:05] [homebridge-cielo] This plugin threw an error from the characteristic 'Target Heating Cooling State': Unhandled error thrown inside write handler for characteristic: log is not defined. See https://homebridge.io/w/JtMGR for more info.
[31/07/2023, 13:01:14] [cielo] Restoring existing accessory from cache: Lower Living

**Comment by jardilio** [comment]
Any update? I see the same error, but it was working previously. I'm also running as a child bridge and it keeps restarting over and over.

**Comment by ryanfroese** [comment]
OK, this should be working now. I had to rewrite due to the API changing on Cielo's end. They added a captcha, so I had to add a captcha service to get mine working.
