### ISSUE TITLE
Console errors in Rasberry PI  Homebridge OS

### ISSUE THREAD

**Issue by aadittmar** [ryanfroese/homebridge-smartcielo#5]
**Describe Your Problem:**
I get this console error when trying to run homebridge-cielo v1.1.5 on my raspberry pi with the Homebridge OS.

**Logs:**
[27/11/2023, 22:15:13] [homebridge-cielo] Launched child bridge with PID 18146
[27/11/2023, 22:15:14] Registering platform 'homebridge-cielo.cielo'
[27/11/2023, 22:15:14] [homebridge-cielo] Loaded homebridge-cielo v1.1.5 child bridge successfully
[27/11/2023, 22:15:14] Loaded 0 cached accessories from cachedAccessories.0EE3BA6B15A6.
[27/11/2023, 22:15:14] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-cielo) is running on port 47230.
TypeError: Cannot read properties of undefined (reading 'user')
    at /var/lib/homebridge/node_modules/homebridge-cielo/node_modules/node-smartcielo-ws/Cielo.js:264:52
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CieloAPIConnection.#getAccessTokenAndSessionId (/var/lib/homebridge/node_modules/homebridge-cielo/node_modules/node-smartcielo-ws/Cielo.js:260:23)
    at CieloAPIConnection.establishConnection (/var/lib/homebridge/node_modules/homebridge-cielo/node_modules/node-smartcielo-ws/Cielo.js:119:5)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-cielo/src/platform.ts:73:7)
TypeError: Cannot read properties of undefined (reading 'sessionId')
    at /var/lib/homebridge/node_modules/homebridge-cielo/node_modules/node-smartcielo-ws/Cielo.js:123:32
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CieloAPIConnection.establishConnection (/var/lib/homebridge/node_modules/homebridge-cielo/node_modules/node-smartcielo-ws/Cielo.js:119:5)
    at HomebridgeAPI.<anonymous> (/var/lib/homebridge/node_modules/homebridge-cielo/src/platform.ts:73:7)
[27/11/2023, 22:15:14] [homebridge-cielo] Child bridge process ended
[27/11/2023, 22:15:14] [homebridge-cielo] Process Ended. Code: 1, Signal: null

**Plugin Config:**
{
    "bridge": {
        "name": "Homebridge AA48",
        "username": "0E:5C:3E:51:AA:48",
        "port": 51996,
        "pin": "725-80-718",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "username": "aadittmar@gmail.com",
            "password": "xxxx",
            "ip": "xxxx",
            "platform": "cielo"
        }
    ],
    "disabledPlugins": []
}

**Environment:**
* **Plugin Version**: v1.1.5
* **Homebridge Version**: 1.7.0
* **Node.js Version**: v18.18.2
* **NPM Version**:  9.8.1
* **Operating System**:  Raspberry PI HomeBridge OS -> Debian GNU/Linux Bookworm (12)

**Comment by fractically** [comment]
*bump*

At this point I'd be happy with "leave me alone, I have no idea what's going wrong", "I don't have time to continue working on this", or even a simple "NO", and I'll give up and move onto another solution. I get it, no one is making money off of whether this works for end users, but it would be great if the person who built this project would say *something*... [Many of us are having the exact same issue](https://github.com/ryanfroese/homebridge-smartcielo/issues/3), so it's not just a single, crazy-weird environmental issue...
